### ISSUE TITLE
Inheritence

### ISSUE THREAD

**Issue by pro9code** [paishee/aepl#1]
can it be an option to still retain props and functs from the parent class? And what about extends for classes?

**Comment by shysolocup** [comment]
as far as I know extends still works fine
```js
const cl = require('aepl')

cl.init("Example", class extends Array {
    constructor() {
        super()
    }
})

let ex = new Example()

ex.push("a");
ex.push("b");

console.log(ex) // ['a', 'b']
```
as far as the other part properties and functions are tied to the class's prototype so my best answer would be to copy the parent's prototype over to the subclass unless I decide to make it a new feature
